services:
  react:
    image: joonyor/ytt-react-amd64-image
    container_name: react_app
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=production
    depends_on:
      - flask
    networks:
      - ytt-network

  flask:
    image: joonyor/ytt-flask-amd64-image
    container_name: flask_app
    ports:
      - "9005:9005"
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis
    networks:
      - ytt-network

  redis:
    image: redis:7   # Use the Redis 7 image
    ports:
      - "6379:6379"  # Map Redis to the default port
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - ytt-network

networks:
  ytt-network:
    driver: bridge