services:
  redis-dev:
    image: redis:7   # Use the Redis 7 image
    ports:
      - "6379:6379"  # Map Redis to the default port
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3